spring:
  profiles.active: default
  application.name: library
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/library}
    username: root
    password:
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true